### ISSUE TITLE
update OKH/W slurpers to handle atom properties

### ISSUE THREAD

**Issue by devhawk** [PubInv/project-data#29]
IN order to make OKH/W types toolable, we have proposed adding several structured data lists to the OKH/W files to represent supply and tool "atoms". These OK* atoms have a unique string identifier (established by WikiData) as well a human-readable description and a URL. The updated OKH/W files have atoms for: BOM and tool list as well as the final output of the OKH and any left over BOM consumables. 

The code that imports OKH/W files (aka "slurpers") needs to be updated to read these properties and generate SymPy symbols from the various identifiers to be used by SupplyProblem/SupplyTree.

Example:
``` yaml
bom-atoms:
  # TODO: size, quantity
  - identifier:
    description: Freshly washed spunbond Non-woven Polypropylene bags (3 sheets, 8″ by 9″)
    link: 
  - description: Bias tape or other latex-free ties (e.g., cotton ties or silicone ties)
    identifier: Q4902580
    link: https://www.wikidata.org/wiki/Q4902580
  - identifier: 
    description: Coffee tin ties
    link: 
  - identifier: Q3355092 
    description: pipe cleaners 
    link: https://www.wikidata.org/wiki/Q3355092
  - identifier: Q8353
    description: coated paper clips
    link: https://www.wikidata.org/wiki/Q8353

tool-list-atoms:
  - identifier: Q49013
    description: Sewing machine 
    link: https://www.wikidata.org/wiki/Q49013
  - identifier: Q40847
    description: Scissors
    link: https://www.wikidata.org/wiki/Q40847
  - identifier: Q111591519
    description: Pins
    link: https://www.wikidata.org/wiki/Q111591519
  - identifier: Q107196205
    description: Measuring tape
    link: https://www.wikidata.org/wiki/Q107196205

product-atom: 
  - identifier: QH00001
    descroption: Fabric Mask

bom-output-atoms:
  - identifier: Q1378670
    description: Scrap Fabric
    link: https://www.wikidata.org/wiki/Q1378670
```
